# Generated by Django 4.0.4 on 2022-04-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('AdminName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('Userfullname', models.CharField(max_length=500)),
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Useremail', models.EmailField(max_length=254)),
                ('Userage', models.IntegerField()),
                ('Usergender', models.CharField(max_length=500)),
                ('UserPhoneNumber', models.CharField(max_length=12)),
                ('UserAddress', models.CharField(max_length=500)),
                ('UserPassword', models.CharField(max_length=500)),
                ('UserProfile', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('Doctorfullname', models.CharField(max_length=500)),
                ('DoctorPhoneNumber', models.CharField(max_length=12)),
                ('DoctorAddress', models.CharField(max_length=500)),
                ('DoctorId', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorCategory', models.CharField(max_length=500)),
                ('DoctorNationalID_front', models.CharField(max_length=500)),
                ('DoctorNationalID_back', models.CharField(max_length=500)),
                ('DoctorPassword', models.CharField(max_length=500)),
            ],
        ),
    ]
