# Generated by Django 4.0.4 on 2022-04-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='SiteAdmin',
        ),
        migrations.RenameModel(
            old_name='client',
            new_name='Siteclient',
        ),
    ]
