# Generated by Django 4.0.4 on 2022-04-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0002_rename_admin_siteadmin_rename_client_siteclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='DoctorId',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
