# Generated by Django 4.0.4 on 2022-04-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0004_remove_doctors_doctorid_doctors_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='DoctorPhoneNumber',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
