# Generated by Django 4.0.4 on 2022-04-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0005_remove_doctors_id_alter_doctors_doctorphonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_offline',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=500)),
                ('doct_name', models.CharField(max_length=500)),
                ('cl_name', models.CharField(max_length=500)),
                ('cl_pnumber', models.CharField(max_length=500)),
                ('b_date', models.DateField()),
            ],
        ),
    ]
