# Generated by Django 4.0.1 on 2022-05-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0006_booking_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_offline',
            name='onLineMeeting',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='booking_offline',
            name='roomName',
            field=models.CharField(default='', max_length=500),
        ),
    ]
