# Generated by Django 4.0.1 on 2022-06-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0007_booking_offline_onlinemeeting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_medicine',
            fields=[
                ('drug_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=500)),
                ('drug_price', models.CharField(max_length=500)),
                ('drug_category', models.CharField(max_length=500)),
                ('drug_desc', models.CharField(max_length=500)),
                ('drug_amount', models.CharField(max_length=500)),
                ('drug_form', models.CharField(max_length=500)),
                ('drug_code', models.CharField(max_length=500)),
            ],
        ),
    ]
