# Generated by Django 4.0.4 on 2022-06-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0009_med_orederd_booking_offline_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_offline',
            name='b_time',
            field=models.TimeField(null=True),
        ),
    ]
