# Generated by Django 4.0.5 on 2022-07-03 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0010_booking_offline_b_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med_orederd',
            name='cl_name',
        ),
        migrations.RemoveField(
            model_name='med_orederd',
            name='med_cout',
        ),
        migrations.RemoveField(
            model_name='med_orederd',
            name='med_name',
        ),
        migrations.RemoveField(
            model_name='med_orederd',
            name='oreder_price',
        ),
        migrations.AddField(
            model_name='med_orederd',
            name='cl_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapi.siteclient'),
        ),
        migrations.AddField(
            model_name='med_orederd',
            name='med_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapi.order_medicine'),
        ),
    ]
