# Generated by Django 4.0.5 on 2022-07-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0012_alter_med_orederd_cl_id_alter_med_orederd_med_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_medicine',
            name='drug_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
