# Generated by Django 4.0.5 on 2022-07-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0013_alter_order_medicine_drug_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med_orederd',
            old_name='med_Id',
            new_name='drug_category',
        ),
        migrations.AddField(
            model_name='med_orederd',
            name='drug_desc',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='med_orederd',
            name='drug_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='med_orederd',
            name='drug_price',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
